version: '3.8'

services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - react_app-network
    ports:
      - "3000:80"

networks:
  react_app-network:
    driver: bridge
